import QRCode from 'qrcode';
import './style.css';

const ROTATE_MS = 20_000;
const SESSION_MS = 8 * 60_000;
const APP_VERSION = '1.1.0';
const storeKey = 'kampus-yoklama-mvp-v1';
let students = [];
let course = { id:27063, code: 'PSK 301', title: 'Fizyolojik Psikoloji', room: '—', day: 'Pazartesi', time: 'OİS haftalık planı' };
const state = JSON.parse(localStorage.getItem(storeKey) || 'null') || { active: null, logs: [], screen: 'dashboard' };
state.completed ??= [];
// Eski TC-giriş oturumunu yeni hoca-kodu akışına taşımayız; yeniden doğrulama gerekir.
if (state.auth && state.auth.loginMethod !== 'instructor-id') { delete state.auth; delete state.mustChangePassword; }
let rotationTimer, tvTimer, lastServerSync=0;

const el = (s) => document.querySelector(s);
const save = () => localStorage.setItem(storeKey, JSON.stringify(state));
// Eski sürüm HTTP 200 yanıtını doğrulanmış teslimat gibi saklayabiliyordu.
// Doğrulanmamış eski özetler yeni QR oturumunda katılım göstermemelidir.
const legacyCompletedCount = state.completed.length;
state.completed = state.completed.filter(item => item.verified === true);
if (state.completed.length !== legacyCompletedCount) save();
const now = () => Date.now();
const fmt = (t) => new Intl.DateTimeFormat('tr-TR', { hour: '2-digit', minute: '2-digit', second: '2-digit' }).format(t);
const safe = (v) => String(v).replace(/[&<>"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const token = () => crypto.getRandomValues(new Uint32Array(4)).join('-');
const api=async(url,options={})=>{const response=await fetch(url,{...options,headers:{...(options.headers||{}),'content-type':'application/json',...(state.auth?{authorization:`Bearer ${state.auth.token}`}:{})}});if(response.status===401&&state.auth){delete state.auth;delete state.mustChangePassword;delete state.selectedCourseId;save();setTimeout(render,0);}return response;};

function log(type, detail, severity = 'normal') {
  state.logs.unshift({ id: token(), at: now(), type, detail, severity });
  state.logs = state.logs.slice(0, 60); save();
}
function activeValid() { return state.active && now() < state.active.endsAt; }
function qrActive() { return activeValid() && state.active.qrOpen; }
function selectedMeeting(){return course.raw?.meetings?.find(x=>x.id===state.selectedMeetingId)||course.raw?.meetings?.find(x=>x.week===state.selectedWeek&&!x.isExamWeek)||course.raw?.meetings?.find(x=>x.week===state.selectedWeek)||course.raw?.meetings?.[0];}
function todaySummary(){const meeting=selectedMeeting();return state.completed.find(x=>x.courseId===course.id&&x.meetingId===meeting?.id);}
function clearTimers() { clearInterval(rotationTimer); clearTimeout(tvTimer); }
async function syncActive(){if(!state.active||now()-lastServerSync<2500)return;lastServerSync=now();const r=await api(`/api/sessions/${state.active.id}`);if(!r.ok)return;const data=await r.json(),next=data.present.map(x=>({id:x.no,name:x.name,checkedAt:x.checkedAt}));if(next.length!==state.active.present.length){state.active.present=next;save();render();}}
async function startSession() {
  const meeting=selectedMeeting(); if(!meeting)return alert('Önce OİS planından bir hafta seçin.');
  const response = await api('/api/sessions',{method:'POST',body:JSON.stringify({courseId:course.id,meetingId:meeting.id,meetingDate:meeting.date,week:meeting.week})});
  const data = await response.json(); if(!response.ok) return alert(data.error||'Oturum açılamadı');
  state.active = { id:data.id, meetingId:data.meetingId, week:data.week, apiWeek:data.apiWeek, meetingDate:data.meetingDate, meetingType:data.meetingType, absenceHours:data.absenceHours, absentField:data.absentField, presentField:data.presentField, startedAt:now(), endsAt:data.closesAt, qrToken:data.challenge, qrIssuedAt:now(), present:(data.present||[]).map(x=>({id:x.no,name:x.name,checkedAt:x.checkedAt})), previouslyDeliveredCount:data.previouslyDeliveredCount||0, qrOpen:true, openNumber:data.openNumber, maxOpens:data.maxOpens||5, opensRemaining:data.opensRemaining };
  log('QR yoklaması açıldı', `${course.code} · hafta ${data.week} · ${data.openNumber}. oturum / ${data.maxOpens||5}`); save(); render();
}
function setActiveSession(data) {
  state.active = { id:data.id, meetingId:data.meetingId, week:data.week, apiWeek:data.apiWeek, meetingDate:data.meetingDate, meetingType:data.meetingType, absenceHours:data.absenceHours, absentField:data.absentField, presentField:data.presentField, startedAt:now(), endsAt:data.closesAt, qrToken:data.challenge, qrIssuedAt:now(), present:(data.present||[]).map(x=>({id:x.no,name:x.name,checkedAt:x.checkedAt})), previouslyDeliveredCount:data.previouslyDeliveredCount||0, qrOpen:true, openNumber:data.openNumber, maxOpens:data.maxOpens||5, opensRemaining:data.opensRemaining };
}
async function startTvPairing() {
  const meeting=selectedMeeting(); if(!meeting)return alert('Önce OİS planından bir hafta seçin.');
  const r=await api('/api/tv/pairings',{method:'POST',body:JSON.stringify({courseId:course.id,meetingId:meeting.id,meetingDate:meeting.date,week:meeting.week})});
  const data=await r.json(); if(!r.ok)return alert(data.error||'TV bağlantısı başlatılamadı.');
  showTvPairingModal(data);
}
function showTvPairingModal(pairing) {
  const modal=document.createElement('div'); modal.style.cssText='position:fixed;inset:0;z-index:9999;background:rgba(0,0,0,.62);display:grid;place-items:center;padding:24px';
  modal.innerHTML=`<section role="dialog" aria-modal="true" class="card" style="width:min(580px,100%);padding:36px;text-align:center"><p class="eyebrow">TV BAĞLANTISI</p><h2>Bu kodu TV ekranında girin.</h2><div id="tv-pair-code" style="font-size:56px;letter-spacing:.16em;font-weight:800;margin:24px 0">${safe(pairing.code)}</div><p id="tv-pair-status" style="color:var(--muted);line-height:1.55">TV’de aynı siteyi açın, “TV ile giriş” seçeneğine basın ve bu kodu girin.</p><button class="primary" id="approve-tv" disabled style="display:none;margin:18px auto">Yoklamayı TV’de başlat</button><button class="ghost" id="cancel-tv-pair" style="margin-top:12px">İptal</button></section>`;
  document.body.append(modal); let closed=false;
  const close=()=>{closed=true;modal.remove();}; modal.querySelector('#cancel-tv-pair').onclick=close;
  const poll=async()=>{if(closed)return;const response=await api(`/api/tv/pairings/${pairing.id}`);const data=await response.json().catch(()=>({}));if(!response.ok){modal.querySelector('#tv-pair-status').textContent=data.error||'Bağlantı kontrol edilemedi.';return;}const status=modal.querySelector('#tv-pair-status');if(data.status==='WAITING_FOR_APPROVAL'){status.textContent='TV bağlandı. Yoklamayı yalnızca siz onayladıktan sonra TV’de QR kod görünecek.';const approve=modal.querySelector('#approve-tv');approve.style.display='block';approve.disabled=false;approve.onclick=async()=>{approve.disabled=true;const approved=await api(`/api/tv/pairings/${pairing.id}/approve`,{method:'POST'}),body=await approved.json();if(!approved.ok){status.textContent=body.error||'Yoklama başlatılamadı.';approve.disabled=false;return;}setActiveSession(body.session);log('TV ile QR yoklaması açıldı',`${course.code} · hafta ${body.session.week}`);save();close();render();};}
    else if(data.status==='EXPIRED'||data.status==='SUPERSEDED'){status.textContent='Bu TV kodunun süresi doldu. Bilgisayardan yeni kod üretin.';return;}
    setTimeout(poll,1200);
  }; poll();
}
async function closeQr() {
  if (!state.active) return;
  const r=await api(`/api/sessions/${state.active.id}/qr-close`,{method:'POST'}),data=await r.json();if(!r.ok)return alert(data.error||'QR kapatılamadı');
  state.active.qrOpen=false;state.active.qrToken=null;state.active.opensRemaining=data.opensRemaining;log('QR yoklaması kapatıldı', `${state.active.present.length} öğrenci korundu`);save();render();
}
async function endClass() {
  if (!state.active) return;
  const r=await api(`/api/sessions/${state.active.id}/end`,{method:'POST',body:JSON.stringify({week:state.active.week})}),data=await r.json();if(!r.ok){if(!data.oisDebug){alert(data.error||'Gönderim başlatılamadı.');return;}state.failedDelivery={courseId:course.id,date:state.active.meetingDate,error:data.detail||data.error,payload:data.oisPayload,debug:data.oisDebug};save();render();return showOisFailureModal(data);}
  const summary=data.summary||{total:students.length,attended:state.active.present.length,absent:Math.max(0,students.length-state.active.present.length),sent:data.delivery?.sent?students.length:0,students:[]};const completed={courseId:course.id,meetingId:state.active.meetingId,date:state.active.meetingDate,week:state.active.week,present:summary.attended,total:summary.total,openNumber:data.openNumber,maxOpens:data.maxOpens||5,endedAt:now(),obsSent:Boolean(data.delivery?.sent),accepted:Boolean(data.delivery?.accepted),verified:Boolean(data.delivery?.verified),delivery:data.delivery};state.completed=state.completed.filter(x=>!(x.courseId===completed.courseId&&x.meetingId===completed.meetingId));state.completed.unshift(completed);delete state.lastDelivery;
  log('Ders bitirildi', data.delivery?.accepted?`${summary.total} öğrenci için OİS API kabul yanıtı alındı; doğrulama bekleniyor`:`${summary.attended} öğrenci için OİS test paketi hazır`);state.active=null;save();render();showDeliverySummaryModal(summary,data.delivery,completed);
}
async function rotate() {
  if (!activeValid()) { return; }
  if (!qrActive()) { await syncActive(); return; }
  if (now() - state.active.qrIssuedAt >= ROTATE_MS) {
    const r=await api(`/api/sessions/${state.active.id}/challenge`), data=await r.json(); if(!r.ok){state.active.qrOpen=false;save();render();return;}
    state.active.qrToken = data.challenge; state.active.qrIssuedAt = now(); log('QR yenilendi', 'Sunucu yeni kısa ömürlü erişim tanıtıcısı üretti'); save();
  }
  await syncActive(); drawLive();
}
async function chooseCourse(c){course={id:c.id,code:c.code,title:c.title,room:c.room||'—',day:'OİS haftalık planı',time:`Şube ${c.section}`,raw:c};students=[];state.selectedCourseId=c.id;const stillSelected=c.meetings?.some(x=>x.id===state.selectedMeetingId);if(!stillSelected){const first=c.meetings?.find(x=>!x.isExamWeek)||c.meetings?.[0];state.selectedWeek=first?.week;state.selectedMeetingId=first?.id;}state.screen='attendance';save();render();try{const r=await api(`/api/courses/${c.id}/ois-students`,{method:'POST'}),d=await r.json();if(!r.ok)throw new Error(d.error);students=d.students.map(s=>({id:s.no,name:s.name,verified:true,department:'OİS',term:c.term}));render();}catch(error){log('OİS öğrenci listesi alınamadı',error.message,'warning');render();}}
async function showStudentStatus(){const meeting=selectedMeeting(),activeForMeeting=activeValid()&&state.active?.meetingId===meeting?.id;let delivered=!activeForMeeting?todaySummary():null;let present=new Set((activeForMeeting?state.active.present:[]||[]).map(student=>student.id));if(!activeForMeeting&&meeting){try{const r=await api(`/api/courses/${course.id}/attendance-history?meetingId=${encodeURIComponent(meeting.id)}`),data=await r.json();if(r.ok&&data.delivered){present=new Set((data.present||[]).map(student=>student.no));delivered={present:present.size,total:students.length,obsSent:true};}}catch{}}const modal=document.createElement('div');modal.style.cssText='position:fixed;inset:0;z-index:9999;background:rgba(0,0,0,.62);display:grid;place-items:center;padding:24px';const statusLabel=delivered?.obsSent?'OİS API kabul etti':'Yoklama durumu';modal.innerHTML=`<section role="dialog" aria-modal="true" class="card" style="width:min(920px,100%);max-height:88vh;overflow:auto;padding:32px"><div class="section-head"><div><p class="eyebrow">OİS ÖĞRENCİ LİSTESİ</p><h2>${safe(course.title)}</h2><p style="color:var(--muted);margin:7px 0 0">${students.length} kayıtlı öğrenci · ${present.size} yoklama alındı · ${safe(statusLabel)}</p></div><button class="ghost" id="close-student-status">Kapat</button></div><div style="overflow:auto;margin-top:18px"><table style="width:100%;border-collapse:collapse;text-align:left"><thead><tr><th style="padding:12px;border-bottom:1px solid #ddd">Öğrenci no</th><th style="padding:12px;border-bottom:1px solid #ddd">Ad soyad</th><th style="padding:12px;border-bottom:1px solid #ddd">Yoklama durumu</th></tr></thead><tbody>${students.map(student=>{const checked=present.has(student.id);return `<tr><td style="padding:13px;border-bottom:1px solid #eee">${safe(student.id)}</td><td style="padding:13px;border-bottom:1px solid #eee">${safe(student.name)}</td><td style="padding:13px;border-bottom:1px solid #eee;color:${checked?'#16803c':'#777'};font-weight:700">${checked?'✓ Yoklama alındı':'○ Bekliyor'}</td></tr>`}).join('')||'<tr><td colspan="3" style="padding:18px">Öğrenci listesi OİS’ten yükleniyor veya bulunamadı.</td></tr>'}</tbody></table></div></section>`;document.body.append(modal);modal.querySelector('#close-student-status').onclick=()=>modal.remove();}
async function readOisProgram(){const button=el('#read-ois-program');if(button){button.disabled=true;button.textContent='OİS programı okunuyor…';}try{const r=await api(`/api/courses/${course.id}/ois-program`),d=await r.json();state.oisProgramProbe={courseId:course.id,data:r.ok?d:{error:d.error,debug:d.oisDebug||null}};save();render();}catch(error){state.oisProgramProbe={courseId:course.id,data:{error:error.message}};save();render();}}
async function loadInstructorProfile(){const season=state.oisSeason||'2025-2026',semester=Number(state.oisSemester||1);try{const r=await api(`/api/instructors/me/profile?season=${encodeURIComponent(season)}&semester=${semester}`),d=await r.json();if(r.ok&&d.instructor?.name)state.auth.instructor={...state.auth.instructor,...d.instructor};}catch{}}
function loginScreen(){
  el('#app').innerHTML=`<main><section class="card" style="max-width:620px;margin:10vh auto;padding:48px"><p class="eyebrow">KAMPÜS YOKLAMA · v${APP_VERSION}</p><h1>Hoş geldiniz.</h1><p style="margin:13px 0 27px;color:var(--muted);line-height:1.5;font-size:14px">Öğretmen bilgisayarından giriş yapın veya sınıf televizyonunu kısa ekran koduyla bağlayın.</p><div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(240px,1fr));gap:18px"><section style="border:1px solid var(--line);border-radius:14px;padding:22px"><p class="eyebrow">SİSTEM GİRİŞİ</p><label>Hoca kodu / yönetici kullanıcı adı<input id="instructor-id" autocomplete="username" placeholder="Hoca kodunuz veya yönetici adınız"></label><label>Şifre<input id="password" type="password" autocomplete="current-password" placeholder="Şifreniz"></label><button class="primary" id="login" style="width:100%;margin-top:14px">Sisteme giriş yap</button><div id="login-result"></div></section><section style="border:1px solid var(--line);border-radius:14px;padding:22px"><p class="eyebrow">SINIF EKRANI</p><h2 style="font-size:24px">TV ile giriş</h2><p style="color:var(--muted);line-height:1.55;font-size:14px">Öğretmenin bilgisayarında üretilen altı haneli ekran kodunu girin. Hoca şifresi TV’de asla yazılmaz.</p><button class="ghost" id="tv-mode" style="margin-top:20px;width:100%">TV kodunu gir</button></section></div></section></main>`;
  el('#login').onclick=async()=>{const username=el('#instructor-id').value.trim(),password=el('#password').value,out=el('#login-result');const r=await fetch('/api/auth/login',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({instructorId:username,password})}),d=await r.json();if(r.ok){state.auth={token:d.token,instructor:d.instructor,loginMethod:'instructor-id'};state.courses=d.courses;state.mustChangePassword=Boolean(d.passwordChangeRequired);delete state.selectedCourseId;if(!state.mustChangePassword)await loadInstructorProfile();state.screen=state.mustChangePassword?'password-setup':'dashboard';save();return render();}const adminResponse=await fetch('/api/admin/login',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({username,password})}),admin=await adminResponse.json();if(!adminResponse.ok)return result(out,'Kullanıcı adı veya şifre hatalı.',false);localStorage.setItem('kampus-yoklama-admin-v1',JSON.stringify({token:admin.token,admin:admin.admin,mustChangePassword:Boolean(admin.passwordChangeRequired)}));location.assign('/admin.html');};
  el('#tv-mode').onclick=tvPairingScreen;
}
function tvPairingScreen(){
  clearTimers();
  el('#app').innerHTML=`<main><section class="card" style="max-width:520px;margin:14vh auto;padding:48px"><p class="eyebrow">SINIF EKRANI · TV MODU</p><h1>TV’yi bağlayın.</h1><p style="color:var(--muted);line-height:1.6;margin:12px 0 24px">Öğretmenin bilgisayarındaki “TV’ye bağla” düğmesinden üretilen altı haneli kodu girin. Öğretmen onayı olmadan ders veya QR görünmez.</p><label>Altı haneli ekran kodu<input id="tv-code" inputmode="numeric" maxlength="6" placeholder="000000" style="font-size:25px;letter-spacing:.22em;text-align:center"></label><button class="primary" id="connect-tv" style="width:100%;margin-top:16px">TV’yi bağla</button><div id="tv-result"></div><button class="ghost" id="teacher-login" style="margin-top:18px">Öğretmen girişine dön</button></section></main>`;
  el('#teacher-login').onclick=loginScreen;
  el('#connect-tv').onclick=async()=>{const out=el('#tv-result'),code=el('#tv-code').value.replace(/\D/g,'');if(code.length!==6)return result(out,'Altı haneli kodu girin.',false);const r=await fetch('/api/tv/connect',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({code})}),d=await r.json();if(!r.ok)return result(out,d.error||'TV bağlanamadı.',false);state.tv={displayToken:d.displayToken};save();render();};
}
async function tvDisplayScreen(){
  const response=await fetch('/api/tv/status',{headers:{'x-tv-display-token':state.tv.displayToken}});
  const data=await response.json().catch(()=>({}));
  if(!response.ok||data.status==='ENDED'||data.status==='EXPIRED'||data.status==='SUPERSEDED'){delete state.tv;save();return tvPairingScreen();}
  if(data.status==='WAITING_FOR_APPROVAL'){
    el('#app').innerHTML=`<main><section class="card" style="max-width:620px;margin:18vh auto;padding:58px;text-align:center"><p class="eyebrow">TV BAĞLANDI</p><h1>Öğretmen onayı bekleniyor.</h1><p style="color:var(--muted);margin-top:15px">Bilgisayardaki öğretmen “Yoklamayı TV’de başlat” onayını verdiğinde QR kod burada görünecek.</p></section></main>`;
  } else if(data.status==='ACTIVE') {
    const qrUrl=data.qrOpen?`${location.origin}/student.html?session=${encodeURIComponent(data.sessionId)}&challenge=${encodeURIComponent(data.challenge)}`:null;
    el('#app').innerHTML=`<main><section class="card" style="max-width:940px;margin:7vh auto;padding:42px;text-align:center"><p class="eyebrow">CANLI YOKLAMA · HAFTA ${safe(data.week)} · ${safe(data.meetingDate)}</p><h1 style="margin:6px 0">${safe(data.course.title)}</h1><p style="color:var(--muted)">${safe(data.course.code)} · Şube ${safe(data.course.section)}</p>${data.qrOpen?`<canvas id="tv-qr" style="margin:26px auto 18px"></canvas><h2>${safe(data.presentCount)} / ${safe(data.total)} öğrenci yoklama verdi</h2><p style="color:var(--muted)">QR kod otomatik yenilenir.</p>`:`<h2 style="margin-top:40px">QR okutma geçici olarak kapalı.</h2><p style="color:var(--muted)">Öğretmenin bilgisayardan yeniden açmasını bekleyin.</p>`}</section></main>`;
    if(qrUrl) await QRCode.toCanvas(el('#tv-qr'),qrUrl,{width:330,margin:1,color:{dark:'#10281f',light:'#f7fcf4'}});
  } else { delete state.tv;save();return tvPairingScreen(); }
  tvTimer=setTimeout(render,2000);
}
function passwordSetupScreen(){el('#app').innerHTML=`<main><section class="card" style="max-width:600px;margin:12vh auto;padding:54px 69px"><p class="eyebrow">HESAP GÜVENLİĞİ</p><h1>Yeni şifre belirleyin.</h1><p style="margin:13px 0 27px;color:var(--muted);line-height:1.6">Dört haneli ilk şifreniz güvenli değildir. Yoklama sistemini açmadan önce yalnızca sizin bileceğiniz yeni bir şifre oluşturun.</p><label>Yeni şifre<input id="new-password" type="password" autocomplete="new-password" placeholder="En az 10 karakter"></label><label>Yeni şifre tekrar<input id="new-password-repeat" type="password" autocomplete="new-password" placeholder="Şifrenizi yeniden girin"></label><small>En az 10 karakter, en az bir harf ve bir rakam kullanın.</small><button class="primary" id="set-password" style="width:100%;margin-top:18px">Şifreyi kaydet ve sisteme devam et</button><div id="password-result"></div></section></main>`;el('#set-password').onclick=async()=>{const value=el('#new-password').value,repeat=el('#new-password-repeat').value;if(value!==repeat)return result(el('#password-result'),'Şifreler aynı değil.',false);const r=await api('/api/auth/password',{method:'POST',body:JSON.stringify({newPassword:value})}),d=await r.json();if(!r.ok)return result(el('#password-result'),d.error,false);state.auth.instructor=d.instructor;delete state.mustChangePassword;await loadInstructorProfile();state.screen='dashboard';save();render();};}
async function logout(){clearTimers();if(state.active){try{await api(`/api/sessions/${state.active.id}/end`,{method:'POST',body:JSON.stringify({week:1})})}catch{}state.active=null;}delete state.auth;state.screen='dashboard';save();render();}
function nav() {
  return `<aside><div class="brand"><span>◈</span><div>KAMPÜS<small>YOKLAMA</small></div></div>
  <nav>${[['dashboard','Genel bakış','▦'],...(state.selectedCourseId?[['attendance','Yoklama ekranı','◷']]:[]),['students','Öğrenciler','♙'],['settings','Ayarlar','⚙'],['audit','Güvenlik kaydı','◉']].map(([id,name,i])=>`<button class="nav ${state.screen===id?'active':''}" data-nav="${id}"><i>${i}</i>${name}</button>`).join('')}</nav>
  <div class="profile"><b>${safe(state.auth.instructor.name)}</b><small>Öğretim elemanı · güvenli oturum</small><button class="ghost" id="logout" style="padding:3px 0;margin-top:5px;font-size:10px">Hesaptan çıkış</button></div></aside>`;
}
function layout(content) { const title={dashboard:'Derslerim',attendance:'Yoklama Merkezi',students:'Öğrenci kayıtları',settings:'Ayarlar',audit:'Denetim günlüğü'}[state.screen]||'Kampüs Yoklama';const period=course.raw?.term||'OİS kaydı';el('#app').innerHTML = `${nav()}<main><header><div><p class="eyebrow">${safe(period)} · v${APP_VERSION}</p><h1>${title}</h1></div><div class="status"><span></span>Güvenli bağlantı</div></header>${content}</main>`; if(state.screen==='dashboard'){el('#ois-query-tool')?.remove();el('#ois-course-result')?.parentElement?.querySelector('details')?.remove();} if(state.screen==='attendance')document.querySelector('#read-ois-program')?.closest('section')?.remove(); bindNav();el('#logout').onclick=logout; }
function bindNav() {
  document.querySelectorAll('[data-nav]').forEach(b=>b.onclick=()=>{state.screen=b.dataset.nav; save(); render();});
  if(state.screen==='dashboard'&&state.oisSeason==='2025-2026'&&Number(state.oisSemester)===3){document.querySelectorAll('[data-ois-course]').forEach(button=>{const item=(state.oisCourses||[]).find(course=>course.id===Number(button.dataset.oisCourse));if(item?.meetingSource==='unavailable'){button.disabled=true;button.style.cursor='not-allowed';button.style.opacity='.55';const status=button.querySelector(':scope > .pill:last-child');if(status)status.textContent='OİS hafta planı bekleniyor';}});}
  const plan=[...document.querySelectorAll('section')].find(section=>section.textContent.includes('AKADEMİK YOKLAMA PLANI'));const badge=plan?.querySelector('.pill');if(badge&&course.raw?.meetings){const weeks=new Set(course.raw.meetings.map(item=>item.week)).size;badge.textContent=`${weeks} hafta · ${course.raw.meetings.length} oturum`;}
  if(state.screen==='attendance'&&!activeValid()&&selectedMeeting()&&el('#open')) { const tvButton=document.createElement('button');tvButton.id='tv-pair';tvButton.className='ghost';tvButton.style.marginLeft='10px';tvButton.textContent='TV’ye bağla';el('#open').insertAdjacentElement('afterend',tvButton);tvButton.onclick=startTvPairing; }
}
function coursesOverview(){ return coursesOverviewEnhanced(); }
let participationLoadKey = '';
function participationKey(courseRow) { return `${courseRow.courseId}:${courseRow.section}`; }
function participationPercent(rate) { return rate === null || rate === undefined ? null : `%${Math.round(rate * 100)}`; }
async function loadInstructorParticipation(season, semester) {
  const loadKey = `${season}:${semester}`;
  if (participationLoadKey === loadKey) return;
  participationLoadKey = loadKey;
  try {
    const response = await api(`/api/instructors/me/participation?season=${encodeURIComponent(season)}&semester=${semester}`);
    const data = await response.json();
    if (!response.ok || state.oisSeason !== season || Number(state.oisSemester) !== Number(semester)) return;
    state.courseParticipation = { season, semester, loadedAt: now(), rows: data.courses || [], summary: data.summary || null };
    save(); render();
  } catch {
    // İstatistik okunamazsa ders listesi ve yoklama akışı çalışmaya devam eder.
  } finally {
    if (participationLoadKey === loadKey) participationLoadKey = '';
  }
}
function coursesOverviewEnhanced() {
  const years=['2022-2023','2023-2024','2024-2025','2025-2026','2026-2027'];
  const selectedSeason=state.oisSeason||'2025-2026';
  const selectedSemester=Number(state.oisSemester||1);
  const courses=state.oisCourses||[];
  const editable=courseItem=>Boolean(courseItem.editable);
  const report=state.courseParticipation;
  const reportIsCurrent=report?.season===selectedSeason&&Number(report?.semester)===selectedSemester;
  const rowsByCourse=new Map((reportIsCurrent?report.rows:[]).map(row=>[participationKey(row),row]));
  const summary=reportIsCurrent?report.summary:null;
  const summaryText=summary?.participationRate===null||summary?.participationRate===undefined
    ? Number(summary?.acceptedAttempts)>0
      ? `${summary.acceptedAttempts} OİS kabul yanıtı alındı; kayıtlar OİS ekranında henüz doğrulanmadı.`
      : 'Bu dönem henüz OİS tarafından doğrulanmış yoklama bulunmuyor.'
    : `Dönem genel katılımı ${participationPercent(summary.participationRate)} · ${summary.coursesWithAttendance}/${summary.totalCourses} derste yoklama doğrulandı.`;
  const courseParticipation=courseItem=>{
    const row=rowsByCourse.get(`${courseItem.id}:${courseItem.section}`);
    if (!row || row.participationRate===null || row.participationRate===undefined) return Number(row?.acceptedAttempts)>0
      ? `<small style="margin-top:8px">${row.acceptedAttempts} OİS kabul yanıtı alındı; kayıt henüz doğrulanmadı.</small>`
      : '<small style="margin-top:8px">Henüz OİS tarafından doğrulanmış yoklama yok.</small>';
    const weekText=row.lastCompletedWeek ? `${row.lastCompletedWeek}. haftaya kadar` : 'İşlenen haftalarda';
    return `<div style="margin-top:9px;display:flex;gap:8px;align-items:center;flex-wrap:wrap"><span class="pill">Genel katılım ${participationPercent(row.participationRate)}</span><small style="margin:0">${weekText} · ${row.sentSessions} doğrulanmış yoklama oturumu</small></div>`;
  };
  const courseHourSummary=courseItem=>{
    const entries=[['Teori',courseItem.theoreticalHours],['Uygulama',courseItem.practicalHours],['Laboratuvar',courseItem.laboratoryHours]]
      .filter(([,hours])=>hours!==null&&hours!==undefined&&hours!=='');
    return entries.length
      ? `<small style="display:block;margin-top:7px">OİS ders saati · ${entries.map(([label,hours])=>`${label}: ${safe(hours)}`).join(' · ')}</small>`
      : '<small style="display:block;margin-top:7px">OİS ders saati bilgisi bulunamadı.</small>';
  };
  layout(`<section class="card"><p class="eyebrow">OİS’TEN DERSLERİMİ GETİR</p><h2>Akademik dönemi seçin.</h2><p style="color:var(--muted);margin:8px 0 22px">Seçim, giriş yapan öğretim elemanının hoca koduyla OİS’e gönderilir; teori, uygulama ve laboratuvar saatleri de aynı ders kaydından alınır.</p><div style="display:grid;grid-template-columns:1.4fr 1fr auto;gap:12px;align-items:end"><label>Akademik yıl<select id="ois-season">${years.map(year=>`<option ${year===selectedSeason?'selected':''}>${year}</option>`).join('')}</select></label><label>Dönem<select id="ois-semester"><option value="1" ${selectedSemester===1?'selected':''}>Güz</option><option value="2" ${selectedSemester===2?'selected':''}>Bahar</option><option value="3" ${selectedSemester===3?'selected':''}>Yaz</option></select></label><button class="primary" id="load-ois-courses">Derslerimi getir</button></div><div id="ois-course-result"></div></section><section class="card" style="margin-top:22px"><div class="section-head"><div><p class="eyebrow">DÖNEM KATILIM ÖZETİ</p><h2>${courses.length?`${courses.length} ders bulundu.`:'Henüz dönem sorgulanmadı.'}</h2><p style="color:var(--muted);margin-top:8px">${safe(summaryText)}</p></div>${courses.length?`<span class="pill">${selectedSeason} · ${{1:'Güz',2:'Bahar',3:'Yaz'}[selectedSemester]}</span>`:''}</div>${courses.map(courseItem=>`<button class="course-line" style="appearance:none;width:100%;text-align:left;background:transparent;border:0;cursor:${editable(courseItem)?'pointer':'not-allowed'};opacity:${editable(courseItem)?'1':'.55'};color:var(--ink);font:300 16px Inter" data-ois-course="${courseItem.id}" ${editable(courseItem)?'':'disabled'}><span class="course-icon">⌘</span><div><b>${safe(courseItem.title)}</b><small>${safe(courseItem.code)} · Şube ${safe(courseItem.section)}</small>${courseHourSummary(courseItem)}<div style="margin-top:9px"><span class="pill">${safe(courseItem.term)}</span></div>${courseParticipation(courseItem)}</div><span class="pill">${editable(courseItem)?'Yoklama ekranını aç →':'Etkin takvim dışı · salt okunur'}</span></button>`).join('')||'<p style="color:var(--muted)">Yıl ve dönem seçip “Derslerimi getir” düğmesine basın.</p>'}</section>`);
  el('#load-ois-courses').onclick=loadOisCourses;
  document.querySelectorAll('[data-ois-course]').forEach(button=>button.onclick=()=>chooseCourse(courses.find(courseItem=>courseItem.id===Number(button.dataset.oisCourse))));
  const newestCompletedAt=Math.max(0,...(state.completed||[]).map(item=>Number(item.endedAt)||0));
  if (courses.length && (!reportIsCurrent || Number(report?.loadedAt||0)<newestCompletedAt || now()-Number(report?.loadedAt||0)>10_000)) void loadInstructorParticipation(selectedSeason, selectedSemester);
}
async function renderOisQueryTool(){const panel=el('#ois-query-tool');if(!panel)return;const season=el('#ois-season')?.value||state.oisSeason||'2025-2026',semester=Number(el('#ois-semester')?.value||state.oisSemester||1);const parameters={method:'hocaders',sezon:season,donem:String(semester),hoca_kodu:state.auth.instructor.id};try{const r=await api('/api/ois/query-tool-config'),config=await r.json();if(!r.ok)throw new Error(config.error);panel.innerHTML=`<p class="eyebrow">OİS SORGU ÖNİZLEMESİ</p><h2>Gönderilecek ders sorgusu</h2><p style="color:var(--muted);line-height:1.55">API kullanıcı adı ve şifresi güvenlik nedeniyle gösterilmez.</p><pre style="white-space:pre-wrap;overflow:auto;background:#111;color:#f5f5f5;padding:15px;border-radius:10px;font-size:12px;margin-top:14px">${safe(JSON.stringify({endpoint:config.endpoint,httpMethod:'GET',parameters},null,2))}</pre>${config.manualTestQueryEnabled?`<details style="margin-top:16px"><summary style="cursor:pointer;font-weight:700">Test için sorguyu düzenle</summary><p style="color:var(--muted);line-height:1.5">Bu geçici araç yalnızca OİS test ortamında açıktır. Testte atanan dersin hoca kodunu girin.</p><div style="display:grid;grid-template-columns:1fr 1fr 1fr auto;gap:10px;align-items:end"><label>Sezon<input id="manual-season" value="${safe(season)}"></label><label>Dönem<select id="manual-semester"><option value="1">Güz</option><option value="2">Bahar</option><option value="3" selected>Yaz</option></select></label><label>Test hoca kodu<input id="manual-hoca-kodu" inputmode="numeric" placeholder="Hoca kodu"></label><button class="primary" id="run-manual-query">Test dersini getir</button></div><div id="manual-query-result"></div></details>`:`<p class="note" style="margin-top:15px">Test sorgusunu düzenleme, yalnızca özel olarak açılmış OİS test ortamında kullanılabilir.</p>`}`;if(config.manualTestQueryEnabled){el('#manual-semester').value=String(semester);el('#run-manual-query').onclick=runManualTestQuery;}}catch(error){panel.innerHTML=`<p class="eyebrow">OİS SORGU ÖNİZLEMESİ</p><h2>Sorgu önizlemesi alınamadı.</h2><p>${safe(error.message)}</p>`;}}
async function runManualTestQuery(){const out=el('#manual-query-result'),season=el('#manual-season').value,semester=Number(el('#manual-semester').value),hocaKodu=el('#manual-hoca-kodu').value.trim();out.textContent='OİS test dersleri sorgulanıyor…';const r=await api('/api/ois/manual-test-query',{method:'POST',body:JSON.stringify({season,semester,hocaKodu})}),d=await r.json();if(!r.ok){out.textContent=d.error||'Test sorgusu başarısız.';return;}state.oisSeason=season;state.oisSemester=semester;state.oisCourses=d.courses;state.oisRaw=d.raw||null;save();render();}
async function loadOisCourses(){const season=el('#ois-season').value,semester=Number(el('#ois-semester').value),out=el('#ois-course-result');out.textContent='OİS’ten dersler okunuyor…';const r=await api(`/api/ois/assigned-courses?season=${encodeURIComponent(season)}&semester=${semester}`),d=await r.json();if(!r.ok){out.textContent=d.error||'Dersler alınamadı.';return;}state.oisSeason=season;state.oisSemester=semester;state.oisCourses=d.courses;state.oisRaw=d.raw||null;if(d.instructor?.name)state.auth.instructor={...state.auth.instructor,name:d.instructor.name,photo:d.instructor.photo||null};save();render();}
function attendanceDashboard() {
  const session = state.active, meeting=selectedMeeting();
  const editable=Boolean(course.raw?.editable);
  const completed=todaySummary(), presentCount=session?.present.length ?? completed?.present ?? 0, totalCount=session?students.length:completed?.total??students.length;
  const maxOpens=session?.maxOpens??completed?.maxOpens??5, nextOpenNumber=(completed?.openNumber??0)+1;
  const startLabel=`${nextOpenNumber}. oturumu başlat (${nextOpenNumber}/${maxOpens})`;
  const allMeetings=course.raw?.meetings||[], weekGroups=[...new Map(allMeetings.map(item=>[item.week,allMeetings.filter(candidate=>candidate.week===item.week)])).entries()].map(([week,items])=>({week,items}));
  const selectedWeekMeetings=allMeetings.filter(item=>item.week===state.selectedWeek);
  const weekdayLabel=value=>({1:'Pazartesi',2:'Salı',3:'Çarşamba',4:'Perşembe',5:'Cuma',6:'Cumartesi',7:'Pazar',pazartesi:'Pazartesi',salı:'Salı',sali:'Salı',çarşamba:'Çarşamba',carsamba:'Çarşamba',perşembe:'Perşembe',persembe:'Perşembe',cuma:'Cuma',cumartesi:'Cumartesi',pazar:'Pazar'})[String(value||'').toLocaleLowerCase('tr-TR')]||String(value||'');
  const meetingTime=item=>item.startTime?(item.endTime?`${safe(item.startTime)}–${safe(item.endTime)}`:safe(item.startTime)):'';
  const meetingLabel=item=>`${item.type==='UYGULAMA'?'Uygulama':'Teori'}${item.day?` · ${safe(weekdayLabel(item.day))}`:''}${meetingTime(item)?` · ${meetingTime(item)}`:''} · ${item.absenceHours} saat`;
  const sameSlot=(left,right)=>Boolean(left&&right&&left.type===right.type&&left.day===right.day&&left.startTime===right.startTime&&left.endTime===right.endTime&&left.absenceHours===right.absenceHours);
  const courseSlots=[...new Map(allMeetings.map(item=>[`${item.type}:${item.day||''}:${item.startTime||''}:${item.endTime||''}:${item.absenceHours}`,item])).values()];
  const weekCards=weekGroups.map(({week,items})=>{const primary=items.find(item=>item.id===meeting?.id)||items[0], exam=items.every(item=>item.isExamWeek);return `<button class="${week===meeting?.week?'primary':'ghost'}" style="min-height:84px;text-align:left" data-week="${week}" ${exam||activeValid()&&week!==state.active.week?'disabled':''}><b>${week}. Hafta${exam?' · Sınav':''}</b><br><small>${safe(primary.date)}</small></button>`;}).join('');
  const activeMeeting=allMeetings.find(item=>item.id===state.active?.meetingId);
  const heroSlots=courseSlots.map(slot=>{const selected=sameSlot(meeting,slot);return `<button class="${selected?'primary':'ghost'}" data-hero-meeting="${safe(slot.id)}" ${activeValid()&&!sameSlot(activeMeeting,slot)?'disabled':''} style="display:block;text-align:left;margin-top:8px;padding:7px 10px">${meetingLabel(slot)}</button>`;}).join('');
  layout(`<button class="ghost" id="back-courses" style="padding:0 0 22px">← Derslerime dön</button><section class="hero"><div><p class="eyebrow">${meeting?`HAFTA ${meeting.week} · ${meeting.date}`:'OTURUM SEÇİN'}</p><h2>${course.title}</h2><p>${course.code} · Şube ${course.raw?.section||'—'}</p><div style="margin-top:12px">${heroSlots}</div></div>${!editable?`<div><b>Salt okunur ders</b><p style="margin:8px 0 0;color:var(--muted)">Geçmiş/aktif olmayan dönem: QR yoklaması açılamaz.</p></div>`:!activeValid()?`<button class="primary" id="open">${startLabel} <b>→</b></button>`:qrActive()?`<div><button class="ghost" id="close-qr">QR okutmayı kapat</button><button class="danger" id="end-class">Dersi bitir ve OİS’e gönder</button></div>`:`<div><button class="primary" id="reopen">QR’ı yeniden aç (${state.active.opensRemaining} hak)</button><button class="danger" id="end-class">Dersi bitir ve OİS’e gönder</button></div>`}</section>
  <section class="card" style="margin-top:22px"><div class="section-head"><div><p class="eyebrow">OİS DERS PROGRAMI</p><h2>Gerçek oturum planını dene.</h2><p style="color:var(--muted);margin:8px 0 0">OİS’in vereceği yanıt, sabit 14 haftayı gerçek planla değiştirmek için kullanılacak.</p></div><button class="ghost" id="read-ois-program">OİS programını getir</button></div>${state.oisProgramProbe?.courseId===course.id?`<details open style="margin-top:14px"><summary style="cursor:pointer;font-weight:700">Son OİS program yanıtı</summary><pre style="white-space:pre-wrap;overflow:auto;background:#111;color:#f5f5f5;padding:15px;border-radius:10px;margin-top:10px;font-size:12px">${safe(JSON.stringify(state.oisProgramProbe.data,null,2))}</pre></details>`:''}</section>
  <section class="card" style="margin-top:24px"><div class="section-head"><div><p class="eyebrow">AKADEMİK YOKLAMA PLANI</p><h2>Yoklama alınacak haftayı seçin.</h2></div><span class="pill">${weekGroups.length} hafta</span></div><div class="note" style="margin:0 0 18px"><b>Takvim kuralı:</b> Sınav haftaları görünür; ancak QR yoklamasına kapalıdır. Dersin gün ve saat bilgisi üstteki ders kartında yer alır.</div><div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(145px,1fr));gap:10px">${weekCards}</div></section>
  ${activeValid()?`<section class="card" id="ois-preview" style="margin-top:22px"><p class="eyebrow">OİS GÖNDERİM ÖNİZLEMESİ</p><h2>Gönderilecek ders verisi hazırlanıyor…</h2><p style="color:var(--muted)">Bu panel API şifresini göstermez.</p></section>`:''}
  <section class="grid stats"><article id="show-students" role="button" tabindex="0" style="cursor:pointer"><small>${completed&&!session?'Tamamlanan yoklama':'Seçili haftanın kaydı'}</small><strong>${presentCount}<em>/ ${totalCount}</em></strong><span>${completed&&!session?(completed.accepted?'OİS API kabul etti · Doğrulama bekleniyor':completed.obsSent?'OİS doğrulandı':'Test paketi hazır'):'Onaylı öğrenci · Listeyi aç'}</span></article><article><small>QR güvenliği</small><strong>${activeValid()?'20 sn':'—'}</strong><span>Dinamik yenileme</span></article><article><small>Hesap güvenliği</small><strong>MFA</strong><span>Öğretim elemanı</span></article></section>
  ${editable?(qrActive()?livePanel():activeValid()?`<section class="empty"><h2>QR yoklaması kapalı</h2><p>${session.present.length} öğrenci kaydı korunuyor. Geç gelenler için QR’ı yeniden açabilir veya ders bittiğinde OİS’e gönderebilirsin.</p><button class="primary" id="reopen2">QR’ı yeniden aç (${state.active.opensRemaining} hak)</button></section>`:`<section class="empty"><div class="empty-icon">▣</div><h2>Yoklama oturumu hazır</h2><p>Bir ders saati için en fazla ${maxOpens} oturum açılabilir. Daha önce OİS’e gönderilmiş öğrenciler yeniden yoklama veremez.</p><button class="primary" id="open2">${startLabel}</button></section>`):''}`);
  el('#back-courses').onclick=()=>{state.screen='dashboard';save();render()};document.querySelectorAll('[data-week]').forEach(button=>button.onclick=()=>{state.selectedWeek=Number(button.dataset.week);state.selectedMeetingId=allMeetings.find(item=>item.week===state.selectedWeek&&!item.isExamWeek)?.id||allMeetings.find(item=>item.week===state.selectedWeek)?.id;save();render();});document.querySelectorAll('[data-hero-meeting]').forEach(button=>button.onclick=()=>{const slot=courseSlots.find(item=>item.id===button.dataset.heroMeeting);const selected=allMeetings.find(item=>item.week===state.selectedWeek&&sameSlot(item,slot));if(selected){state.selectedMeetingId=selected.id;save();render();}});el('#show-students')?.addEventListener('click',showStudentStatus);el('#read-ois-program')?.addEventListener('click',readOisProgram);el('#open')?.addEventListener('click', startSession); el('#open2')?.addEventListener('click', startSession);el('#reopen')?.addEventListener('click',startSession);el('#reopen2')?.addEventListener('click',startSession);el('#close-qr')?.addEventListener('click',closeQr);el('#end-class')?.addEventListener('click',endClass);drawLive();loadOisPreview();
}
async function loadOisPreview(){if(!state.active||!el('#ois-preview'))return;const panel=el('#ois-preview');try{const r=await api(`/api/sessions/${state.active.id}/ois-preview`),d=await r.json();if(!r.ok)throw new Error(d.error);const details=[['Hedef ortam',d.deliveryTarget?.label||'OİS'],['OİS adresi',d.deliveryTarget?.endpoint||'—'],['Ders adı',d.course.title],['Ders kodu',d.course.code],['Ders ID',d.course.id],['Öğretim elemanı',`${d.instructor.name} · ${d.instructor.id}`],['Sezon',d.course.academicYear],['Dönem',d.course.semester],['Şube (section)',d.course.section],['Ekrandaki hafta',d.week],['Gönderilen API haftası',d.apiWeek],['Tarih',d.date],['Gelmemiş öğrenci alanı',`${d.absentField} · ${d.absenceHours}`],['Gelen öğrenci alanı',`${d.presentField} · 0`]].map(([label,value])=>`<div><small>${safe(label)}</small><b style="word-break:break-word">${safe(value)}</b></div>`).join('');const students=d.payload.ogrenciler_saat.map(row=>`<li><b>${safe(row.ogrenci_no)}</b> → ${safe(row.saat??row.usaat??row.Usaat)} saat</li>`).join('');const failure=state.failedDelivery?.courseId===course.id&&state.failedDelivery?.date===d.date?`<div class="result no" style="display:block;margin-top:16px">Son OİS yanıtı: ${safe(state.failedDelivery.error)}</div><details style="margin-top:14px"><summary style="cursor:pointer;font-weight:700">Şifresiz teknik gönderim çıktısı</summary><pre style="white-space:pre-wrap;overflow:auto;background:#111;color:#f5f5f5;padding:15px;border-radius:10px;margin-top:10px;font-size:12px">${safe(JSON.stringify(state.failedDelivery.debug||{parameters:{ders:state.failedDelivery.payload?.ders,ogrenciler_saat:state.failedDelivery.payload?.ogrenciler_saat}},null,2))}</pre></details>`:'';panel.innerHTML=`<div class="section-head"><div><p class="eyebrow">OİS GÖNDERİM ÖNİZLEMESİ</p><h2>Bu değerler OİS’e gönderilecek.</h2></div><span class="pill">${safe(d.deliveryTarget?.label||'OİS')} · şifre gösterilmez</span></div><div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(160px,1fr));gap:14px;line-height:1.45">${details}</div><div class="note" style="margin-top:19px"><b>Öğrenci devamsızlık değerleri</b><ul style="margin:8px 0 0;padding-left:18px">${students}</ul></div>${failure}`;}catch(error){panel.innerHTML=`<p class="eyebrow">OİS GÖNDERİM ÖNİZLEMESİ</p><h2>Önizleme alınamadı.</h2><p>${safe(error.message)}</p>`}}
function livePanel() { const s=state.active; return `<section class="live"><div class="qr-card"><p class="eyebrow">CANLI YOKLAMA</p><canvas id="qr"></canvas><div class="qr-footer"><span class="pulse"></span><span id="qr-age">QR hazırlanıyor…</span></div></div><div class="live-info"><p class="eyebrow">${course.code} · ${course.room}</p><h2>Öğrenciler QR’ı telefonlarından okutur.</h2><p>QR yalnızca aktif oturum, doğrulanmış öğrenci hesabı ve zaman penceresi için geçerlidir.</p><div class="timer"><span>Kalan oturum süresi</span><b id="countdown">--:--</b></div><div class="security-list"><span>✓ Tek öğrenci / tek kayıt</span><span>✓ Eski QR otomatik reddedilir</span><span>✓ Cihaz ve IP olay günlüğü</span></div></div><div class="checkin"><p class="eyebrow">DEMO ÖĞRENCİ DOĞRULAMA</p><label>Öğrenci numarası<input id="student-id" placeholder="2024001" inputmode="numeric"></label><label>QR erişim anahtarı<input id="scan-token" placeholder="QR okutulunca otomatik gelir"></label><button class="primary" id="checkin">Kimliğimi doğrula ve yoklama ver</button><small>Üretimde: üniversite SSO + cihazda WebAuthn / biyometrik onay.</small><div id="result"></div></div></section>`; }
async function drawLive() {
  if (!qrActive() || !el('#qr')) return;
  const s=state.active, remaining=Math.max(0, ROTATE_MS-(now()-s.qrIssuedAt));
  const payload = `${location.origin}/student.html?session=${encodeURIComponent(s.id)}&challenge=${encodeURIComponent(s.qrToken)}`;
  await QRCode.toCanvas(el('#qr'), payload, { width: 210, margin: 1, color: { dark:'#10281f', light:'#f7fcf4' }});
  const age=el('#qr-age'), count=el('#countdown');
  if(age) age.textContent=`Yeni QR ${Math.ceil(remaining/1000)} sn sonra üretilecek`;
  if(count) { const left=Math.max(0,s.endsAt-now()), m=String(Math.floor(left/60000)).padStart(2,'0'), sec=String(Math.floor(left/1000)%60).padStart(2,'0'); count.textContent=`${m}:${sec}`; }
  const tokenInput=el('#scan-token'); if(tokenInput && !tokenInput.value) tokenInput.placeholder = `Demo anahtarı: ${s.qrToken}`;
}
async function checkIn() {
  const studentId=el('#student-id').value.trim(), submitted=el('#scan-token').value.trim(); const out=el('#result');
  if (!qrActive()) return result(out, 'QR yoklaması kapalı veya süresi dolmuş.', false);
  const student=students.find(x=>x.id===studentId);
  if (!student || !student.verified) { log('Reddedilen doğrulama', `Bilinmeyen/doğrulanmamış öğrenci: ${studentId||'boş'}`, 'warn'); return result(out,'Öğrenci hesabı doğrulanamadı.',false); }
  if (submitted !== state.active.qrToken) { log('Reddedilen QR', `${studentId} için geçersiz ya da eski QR`, 'warn'); return result(out,'Bu QR geçersiz veya süresi dolmuş.',false); }
  // QR içindeki challenge doğrudan yoklama kaydı için kullanılmaz. Sunucu önce
  // kısa ömürlü bir doğrulama bileti üretir; bu bilet olmadan kayıt reddedilir.
  const validationResponse=await fetch(`/api/checkin/validate?session=${encodeURIComponent(state.active.id)}&challenge=${encodeURIComponent(submitted)}`), validation=await validationResponse.json();
  if(!validationResponse.ok)return result(out,validation.error||'QR doğrulanamadı.',false);
  const response=await fetch('/api/attendance/claim',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({sessionId:state.active.id,ticket:validation.ticket,studentNo:studentId})}), data=await response.json();
  if(!response.ok)return result(out,data.error||'Yoklama kaydedilemedi.',false);
  const attendance={...student, checkedAt:now(), device:'Onaylı mobil cihaz', ip:'Kayıtlı ağ bölgesi'}; state.active.present.push(attendance); log('Yoklama kaydedildi', `${student.id} · ${student.name}`); save(); result(out,`${student.name}, yoklaman kaydedildi.`,true); render();
}
function result(out, text, yes) { out.className=`result ${yes?'yes':'no'}`; out.textContent=text; }
function showOisFailureModal(data){const debug=data.oisDebug||{environmentLabel:'OİS',endpoint:'OİS yanıtı alınamadı',httpMethod:'GET',parameters:{method:'yoklama',ders:data.oisPayload?.ders,ogrenciler_saat:data.oisPayload?.ogrenciler_saat},response:data.detail||data.error};const report={environment:debug.environmentLabel||debug.environment,endpoint:debug.endpoint,httpMethod:debug.httpMethod,transport:debug.transport||null,parameters:debug.parameters,httpStatus:debug.httpStatus,networkError:debug.networkError||null,response:debug.response};const modal=document.createElement('div');modal.style.cssText='position:fixed;inset:0;z-index:9999;background:rgba(0,0,0,.62);display:grid;place-items:center;padding:24px';modal.innerHTML=`<section role="dialog" aria-modal="true" class="card" style="width:min(900px,100%);max-height:88vh;overflow:auto;padding:32px"><div class="section-head"><div><p class="eyebrow">OİS GÖNDERİM RAPORU</p><h2>OİS isteği reddetti.</h2></div><button class="ghost" id="close-ois-report">Kapat</button></div><div class="result no" style="display:block;margin:12px 0 20px">${safe(data.detail||data.error||'Bilinmeyen hata')}</div><div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:12px;margin-bottom:18px"><div><small>Hedef ortam</small><b>${safe(debug.environmentLabel||debug.environment||'OİS')}</b></div><div><small>Gönderim yöntemi</small><b>${safe(debug.httpMethod||'GET')}</b></div><div><small>Endpoint</small><b style="word-break:break-all">${safe(debug.endpoint||'—')}</b></div><div><small>HTTP durumu</small><b>${safe(debug.httpStatus||'—')}</b></div></div><p style="color:var(--muted);font-size:13px;line-height:1.5">Aşağıdaki değerler sunucudan OİS’e ayrı parametreler halinde gönderildi. API kullanıcı adı ve şifresi güvenlik nedeniyle bu raporda yer almaz.</p><pre style="white-space:pre-wrap;overflow:auto;background:#111;color:#f5f5f5;padding:16px;border-radius:10px;font-size:12px;line-height:1.55">${safe(JSON.stringify(report,null,2))}</pre><button class="primary" id="close-ois-report-bottom" style="float:right">Raporu kapat</button></section>`;document.body.append(modal);const close=()=>modal.remove();modal.querySelector('#close-ois-report').onclick=close;modal.querySelector('#close-ois-report-bottom').onclick=close;}
function showDeliverySummaryModal(summary, delivery, completed) {
  const modal=document.createElement('div');
  modal.style.cssText='position:fixed;inset:0;z-index:9999;background:rgba(0,0,0,.62);display:grid;place-items:center;padding:24px';
  const rows=(summary.students||[]).map(student=>`<tr><td style="padding:13px;border-bottom:1px solid #eee">${safe(student.no)}</td><td style="padding:13px;border-bottom:1px solid #eee">${safe(student.name)}</td><td style="padding:13px;border-bottom:1px solid #eee;color:${student.attended?'#16803c':'#777'};font-weight:700">${student.attended?'✓ Yoklama alındı':'○ Gelmedi'}</td><td style="padding:13px;border-bottom:1px solid #eee;color:#9a6700;font-weight:700">⌛ OİS yanıtı alındı; kayıt doğrulanmadı</td></tr>`).join('');
  const diagnostics=delivery?.diagnostics||null;
  const diagnosticReport=diagnostics?{httpStatus:diagnostics.httpStatus,transport:diagnostics.transport,endpoint:diagnostics.endpoint,request:diagnostics.request,rawResponse:diagnostics.rawResponse}:{deliveryMode:delivery?.mode||null,serverResponse:delivery?.response||delivery?.message||'Sunucu ayrıntısı alınamadı.'};
  const diagnosticPanel=`<details open style="margin:22px 0 0"><summary style="cursor:pointer;font-weight:700">OİS sunucusunun gerçek yanıtı ve gönderim ayrıntısı</summary><p style="color:var(--muted);font-size:13px;line-height:1.5;margin:10px 0">Bu alan OİS’in döndürdüğü ham yanıtı ve şifresiz istek verisini gösterir. API kullanıcı adı ve şifresi asla gösterilmez.</p><pre style="white-space:pre-wrap;overflow:auto;background:#111;color:#f5f5f5;padding:16px;border-radius:10px;font-size:12px;line-height:1.55">${safe(JSON.stringify(diagnosticReport,null,2))}</pre></details>`;
  modal.innerHTML=`<section role="dialog" aria-modal="true" class="card" style="width:min(1040px,100%);max-height:88vh;overflow:auto;padding:32px"><div class="section-head"><div><p class="eyebrow">OİS GÖNDERİM ÖZETİ</p><h2>OİS yanıt verdi; kayıt doğrulanmadı.</h2><p style="color:var(--muted);margin-top:8px">${safe(delivery?.environmentLabel||'OİS')} · ${safe(completed.week)}. hafta · ${safe(completed.date)}</p></div><button class="ghost" id="close-delivery-summary">Kapat</button></div><div class="note" style="margin-top:18px"><b>Bu sonuç OİS kaydının oluştuğunu kanıtlamaz.</b><p style="margin:8px 0 0;line-height:1.5">${safe(delivery?.verificationNote||'OİS raporunda görünene kadar bu istek doğrulanmamış kabul edilir.')}</p></div><div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:11px;margin:22px 0"><div class="note"><small>OİS’te doğrulanan kayıt</small><strong style="font-size:30px;display:block;margin-top:8px">${summary.sent}</strong></div><div class="note"><small>Yoklama alınan</small><strong style="font-size:30px;display:block;margin-top:8px;color:#16803c">${summary.attended}</strong></div><div class="note"><small>Gelmedi</small><strong style="font-size:30px;display:block;margin-top:8px">${summary.absent}</strong></div><div class="note"><small>Oturum hakkı</small><strong style="font-size:30px;display:block;margin-top:8px">${completed.openNumber}/${completed.maxOpens}</strong></div></div><div style="overflow:auto"><table style="width:100%;border-collapse:collapse;text-align:left"><thead><tr><th style="padding:12px;border-bottom:1px solid #ddd">Öğrenci no</th><th style="padding:12px;border-bottom:1px solid #ddd">Ad soyad</th><th style="padding:12px;border-bottom:1px solid #ddd">Yoklama durumu</th><th style="padding:12px;border-bottom:1px solid #ddd">Gönderim durumu</th></tr></thead><tbody>${rows||'<tr><td colspan="4" style="padding:18px">Öğrenci listesi bulunamadı.</td></tr>'}</tbody></table></div>${diagnosticPanel}<button class="primary" id="close-delivery-summary-bottom" style="float:right;margin-top:22px">Tamam</button></section>`;
  document.body.append(modal); const close=()=>modal.remove(); modal.querySelector('#close-delivery-summary').onclick=close;modal.querySelector('#close-delivery-summary-bottom').onclick=close;
}
function studentCheckin(challenge) {
  const valid = activeValid() && state.active.qrToken === challenge;
  el('#app').innerHTML = `<main><section class="card" style="max-width:520px;margin:12vh auto;padding:34px"><p class="eyebrow">GÜVENLİ YOKLAMA</p><h1>${valid ? course.title : 'QR geçersiz'}</h1><p style="color:var(--muted);line-height:1.7;font-size:13px;margin:13px 0 24px">${valid ? 'Ders oturumu açık. Kurum hesabınla kimliğini doğrulayıp yoklamanı ver.' : 'Bu QR artık geçerli değil. Sınıftaki güncel QR’ı yeniden okutun.'}</p>${valid ? `<label style="display:block;font-size:12px;font-weight:700">Öğrenci numarası<input id="mobile-student-id" placeholder="Örn. 2024001" inputmode="numeric" style="display:block;width:100%;margin:7px 0 13px;padding:12px;border:1px solid var(--line);border-radius:7px"></label><div style="font-size:11px;background:#eaf5e7;color:var(--green);padding:11px;border-radius:7px;margin-bottom:14px">✓ Bu cihazda öğrenci hesabı ve biyometrik onay doğrulanacak.</div><button class="primary" style="width:100%" id="mobile-checkin">Kimliğimi doğrula</button><div id="mobile-result"></div>` : `<a class="primary" href="${location.pathname}">Ana sayfaya dön</a>`}<small style="line-height:1.6;margin-top:17px">Demo ortamı: gerçek kurulumda bu ekran üniversite SSO ve WebAuthn/passkey doğrulamasına devredilir.</small></section></main>`;
  el('#mobile-checkin')?.addEventListener('click', () => {
    const studentId = el('#mobile-student-id').value.trim(), student = students.find(x => x.id === studentId), out = el('#mobile-result');
    if (!student || !student.verified) { log('Reddedilen doğrulama', `Bilinmeyen öğrenci: ${studentId||'boş'}`, 'warn'); return result(out, 'Kurum hesabı doğrulanamadı.', false); }
    if (!activeValid() || state.active.qrToken !== challenge) { log('Reddedilen QR', `${student.id} için süresi dolmuş QR`, 'warn'); return result(out, 'QR süresi doldu. Güncel QR’ı okutun.', false); }
    if (state.active.present.some(p => p.id === student.id)) { log('Tekrar yoklama engellendi', `${student.id} · ${student.name}`, 'warn'); return result(out, 'Yoklamanız daha önce kaydedilmiş.', false); }
    state.active.present.push({...student, checkedAt: now(), device:'Onaylı mobil cihaz', ip:'Kayıtlı ağ bölgesi'}); log('Yoklama kaydedildi', `${student.id} · ${student.name}`); save(); result(out, `Başarılı. ${student.name}, yoklamanız kaydedildi.`, true);
  });
}
function sessions() { layout(`<section class="card table"><div class="section-head"><div><p class="eyebrow">TANIMLAR</p><h2>Ders ve haftalık oturumlar</h2></div><button class="primary" id="add">+ Oturum tanımla</button></div><div class="course-line"><span class="course-icon">⌘</span><div><b>${course.title}</b><small>${course.code} · ${course.room} · ${students.length} kayıtlı öğrenci</small></div><span class="pill green">Yayınlandı</span></div>${['07 Ağustos 2026 · 10:00–11:40','14 Ağustos 2026 · 10:00–11:40','21 Ağustos 2026 · 10:00–11:40'].map((x,i)=>`<div class="row"><div class="date"><b>${String(7+i*7).padStart(2,'0')}</b><span>Ağu</span></div><div><b>${x}</b><small>Hafta ${i+1} · ${course.room}</small></div><span class="pill">${i===0&&activeValid()?'Canlı':'Planlandı'}</span></div>`).join('')}</section>`); el('#add').onclick=()=>alert('MVP: üretimde bu form bölüm, dönem, ders ve tekrar kuralı seçerek oturum oluşturur.'); }
function studentsPage() { layout(`<section class="card table"><div class="section-head"><div><p class="eyebrow">${course.code}</p><h2>Derse kayıtlı öğrenciler</h2></div><button class="primary" id="add">+ Öğrenci ekle</button></div>${students.map(s=>`<div class="student-row"><span class="avatar">${s.name.split(' ').map(x=>x[0]).join('')}</span><div><b>${s.name}</b><small>${s.id} · ${s.department}</small></div><span class="verified">✓ Kimliği doğrulandı</span></div>`).join('')}</section><section class="note"><b>Kimlik politikası</b><p>Öğrenci kaydı kurum kimlik sağlayıcısındaki benzersiz kullanıcıyla eşleştirilir. Numara tek başına üretimde yoklama veremez.</p></section>`); el('#add').onclick=()=>alert('MVP: üretimde CSV içe aktarma ve öğrenci bilgi sistemi eşleştirmesi eklenir.'); }
function settingsPageLegacy(){layout(`<section></section>`);}
function settingsPage(){layout(`<section class="card" style="max-width:760px"><p class="eyebrow">${course.code} · 2026–2027 GÜZ</p><h2>14 haftalık ders planı</h2><p style="margin:12px 0 25px;color:var(--muted);font-size:14px">Her günün teori veya uygulama türünü ayrı belirleyin. OBS’ye doğru devamsızlık alanı gönderilir.</p><div style="display:grid;gap:11px"><label><input type="checkbox" value="Salı" checked> Salı <select id="type-Salı"><option value="UYGULAMA">Uygulama</option><option value="TEORI">Teori</option></select></label><label><input type="checkbox" value="Perşembe" checked> Perşembe <select id="type-Perşembe"><option value="TEORI">Teori</option><option value="UYGULAMA">Uygulama</option></select></label><label><input type="checkbox" value="Pazartesi"> Pazartesi <select id="type-Pazartesi"><option value="TEORI">Teori</option><option value="UYGULAMA">Uygulama</option></select></label></div><div style="display:grid;grid-template-columns:repeat(3,1fr);gap:11px;margin:25px 0"><label>Dönem başlangıcı<input id="term-start" type="date" value="2026-09-21"></label><label>Başlangıç<input id="lesson-start" value="10:00"></label><label>Bitiş<input id="lesson-end" value="11:40"></label></div><button class="primary" id="save-schedule">14 haftalık planı kaydet</button><div id="schedule-result"></div></section>`);el('#save-schedule').onclick=async()=>{const days=[...document.querySelectorAll('input[type=checkbox]:checked')].map(x=>x.value),dayTypes=Object.fromEntries(days.map(day=>[day,el(`#type-${day}`).value])),r=await api(`/api/courses/${course.id}/schedule`,{method:'POST',body:JSON.stringify({days,dayTypes,start:el('#lesson-start').value,end:el('#lesson-end').value,termStart:el('#term-start').value})}),d=await r.json();if(r.ok){course.day=days.join(' · ');course.time=`${el('#lesson-start').value}–${el('#lesson-end').value}`;}result(el('#schedule-result'),r.ok?`${d.meetings.length} oturum oluşturuldu. Salı: ${dayTypes.Salı||'—'}, Perşembe: ${dayTypes.Perşembe||'—'}.`:d.error,r.ok)};}
function addPasswordSettings(){const box=document.createElement('section');box.className='card';box.style.maxWidth='760px';box.innerHTML=`<p class="eyebrow">HESAP GÜVENLİĞİ</p><h2>Şifre değiştir</h2><label>Yeni şifre<input id="new-password" type="password"></label><button class="primary" id="change-password">Şifreyi güncelle</button><div id="password-result"></div>`;document.querySelector('main').append(box);el('#change-password').onclick=async()=>{const r=await api('/api/auth/password',{method:'POST',body:JSON.stringify({newPassword:el('#new-password').value})}),d=await r.json();result(el('#password-result'),r.ok?'Şifreniz güncellendi.':d.error,r.ok)}}
function audit() { layout(`<section class="card table"><div class="section-head"><div><div><p class="eyebrow">DEĞİŞTİRİLEMEZ KAYIT</p><h2>Güvenlik olayları</h2></div><button class="ghost" id="export">CSV dışa aktar</button></div>${(state.logs.length?state.logs:[{at:now(),type:'Sistem hazır',detail:'Henüz olay kaydı bulunmuyor.',severity:'normal'}]).map(x=>`<div class="log ${x.severity}"><span>${x.severity==='warn'?'!':'✓'}</span><div><b>${safe(x.type)}</b><small>${safe(x.detail)}</small></div><time>${fmt(x.at)}</time></div>`).join('')}</section><section class="note"><b>Üretim denetim standardı</b><p>Append-only audit tablosu; olay kimliği, kullanıcı, oturum, IP ağ özeti, cihaz bağlamı, sonuç ve önceki-kayıt hash’i tutulur. Ayrı erişim rolü olmadan değiştirilemez.</p></section>`); el('#export').onclick=()=>{ const csv=['zaman,olay,detay',...state.logs.map(x=>`${new Date(x.at).toISOString()},"${x.type}","${x.detail}"`)].join('\n'); const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='yoklama-denetim.csv';a.click();}; }
function render() { clearTimers(); if(state.tv?.displayToken)return tvDisplayScreen(); if(!state.auth)return loginScreen(); if(state.mustChangePassword)return passwordSetupScreen(); if(!activeValid() && state.active) { state.active=null; save(); } const query=new URLSearchParams(location.search).get('checkin'); if(query) return studentCheckin(query); ({dashboard:coursesOverview,attendance:attendanceDashboard,sessions:attendanceDashboard,students:studentsPage,settings:settingsPage,audit})[state.screen](); if(state.screen==='settings')addPasswordSettings(); if(activeValid()) { rotationTimer=setInterval(rotate,1000); el('#checkin')?.addEventListener('click',checkIn); } }
render();
